module.exports = {
  ADD_TRACKS: 'ADD_TRACKS',
  REMOVE_TRACKS: 'REMOVE_TRACKS',
  MODIFY_TRACK: 'MODIFY_TRACK',
  SOCKET_OPENED: 'SOCKET_OPENED',
  SOCKET_CLOSED: 'SOCKET_CLOSED',
  SET_REMOTE_PORT: 'SET_REMOTE_PORT',
  SET_REMOTE_NAME: 'SET_REMOTE_NAME'
};
